---
- name: install basic_packages
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - git
    - tig
    - ranger
    - screen
    - wget
    - w3m
    - unzip
    - ack

- name: install basic_packages_2
  pacman: name={{ item }} state=present
  with_items:
    - fcron
    - docker

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - fcron
    - docker

- command: pacman -Scc

- name: pip
  stat: path=/usr/bin/pip
  register: result
- shell: easy_install-2.7 pip
  when: not result.stat.exists
