---
- name: install basic_packages
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - git
    - tig
    - ranger
    - screen
    - wget
    - w3m
    - unzip
    - ack

- name: install basic_packages_2
  pacman: name={{ item }} state=present
  with_items:
    - fcron
    - docker

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - fcron
    - docker

- command: pacman -Scc


- name: fig
  stat: path=/usr/local/bin/fig
  register: result
- shell: "curl -L https://github.com/docker/fig/releases/download/1.0.1/fig-Linux-x86_64 > /usr/local/bin/fig"
  when: not result.stat.exists
- command: "chmod +x /usr/local/bin/fig"
  when: not result.stat.exists
