---
- name: install basic_packages
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - git
    - tig
    - zsh
    - ranger
    - cronie
    - wget
    - w3m
    - unzip
    - docker

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - cronie
    - docker
