---
- name: install virt-manager
  pacman: name={{ item }} state=present
  with_items:
    - qemu
    - virt-manager
    - libvirt
- service: name=libvirtd state=started enabled=yes


- name: install vncserver
  pacman: name={{ item }} state=present
  with_items:
    - tigervnc
    - ttf-sazanami
    - awesome
    - xterm
- file: path=/root/.vnc/ state=directory
- copy: >
    src=xstartup
    dest=/root/.vnc/xstartup
    mode=0700
- shell: echo password | vncpasswd -f > /root/.vnc/passwd
