---
- name: find {{ php_log }}
  stat: path={{ php_log }}
  register: result

- name: create {{ php_log }}
  file: path={{ php_log }} owner=apache group=apache mode=0644 state=touch
  when: not result.stat.exists

- name: install php
  yum: pkg={{ item }} state=installed
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-gd
    - php-cli
  notify:
    - restart httpd

#- name: Check php.ini.orig
#  stat: path="/etc/php.ini.orig"
#  register: php_ini_patch

#- action: template src="templates/php.ini" dest="/etc/php.ini"
#  when: not php_ini_patch.stat.exists
